// screens

export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const SIGN_UP_SCREEN_1 = 'SIGN_UP_SCREEN_1';
export const SIGN_UP_SCREEN_2 = 'SIGN_UP_SCREEN_2';
export const SIGN_UP_SCREEN_3 = 'SIGN_UP_SCREEN_3';
export const SIGN_UP_SCREEN_4 = 'SIGN_UP_SCREEN_4';
export const SIGN_UP_SCREEN_5 = 'SIGN_UP_SCREEN_5';
export const SIGN_UP_SCREEN_6 = 'SIGN_UP_SCREEN_6';
export const REVIEW_SCREEN = 'REVIEW_SCREEN';
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const USER_PROFILE_SCREEN = 'USER_PROFILE_SCREEN';
export const EMERGENCY_SCREEN = 'EMERGENCY_SCREEN';
export const WORK_SCREEN = 'WORK_SCREEN';
export const HR_SCREEN = 'HR_SCREEN';
export const CURRENT_JOB_SCREEN = 'CURRENT_JOB_SCREEN';
export const COMPLETED_RECORD_SCREEN = 'COMPLETED_RECORD_SCREEN';
export const GUIDE_SCREEN = 'GUIDE_SCREEN';
export const LEAVE_SCREEN = 'LEAVE_SCREEN';
export const TIME_CAPTURE_SCREEN = 'TIME_CAPTURE_SCREEN';
export const PAYMENT_SCREEN = 'PAYMENT_SCREEN';

export const AUTH_ROUTES = 'AUTH_ROUTES';
export const DRAWER_ROUTES = 'DRAWER_ROUTES';
export const HOME_ROUTES = 'HOME_ROUTES';
export const TAB_ROUTES = 'TAB_ROUTES';
export const WORK_ROUTES = 'WORK_ROUTES';
export const USER_PROFILE_ROUTES = 'USER_PROFILE_ROUTES';

// user actions
export const USER_REGISTER = 'USER_REGISTER';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const SET_REGISTER_DETAILS = 'SET_REGISTER_DETAILS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const CHECK_EMAIL = 'CHECK_EMAIL';
export const CHECK_STATUS = 'CHECK_STATUS';
export const UPLOAD_DOCUMENTS = 'UPLOAD_DOCUMENTS';
export const GET_ADMIN_LIST = 'GET_ADMIN_LIST';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_PROFILE_PIC = 'GET_PROFILE_PIC';
export const UPLOAD_PROFILE_PIC = 'UPLOAD_PROFILE_PIC';
export const UPDATE_PROFILE_PIC = 'UPDATE_PROFILE_PIC';
export const GET_JOB_TYPES = 'GET_JOB_TYPES';
export const GET_CHAT_BY_USER = 'GET_CHAT_BY_USER';
export const SET_CHAT_BY_USER = 'SET_CHAT_BY_USER';
export const GET_COMPLETED_RECORDS = 'GET_COMPLETED_RECORDS';
export const SET_COMPLETED_RECORDS = 'SET_COMPLETED_RECORDS';
export const UPLOAD_INVOICE = 'UPLOAD_INVOICE';

// common actions
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER = 'SET_USER';
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const SET_USER_LOGGED_OUT = 'SET_USER_LOGGED_OUT';
export const GET_USER_JOBS = 'GET_USER_JOBS';
export const GET_USER_JOBS_SUCCESS = 'GET_USER_JOBS_SUCCESS';
export const SET_CURRENT_JOB = 'SET_CURRENT_JOB';
export const END_CURRENT_JOB = 'END_CURRENT_JOB';
export const END_CURRENT_JOB_SUCCESS = 'END_CURRENT_JOB_SUCCESS';
export const SET_CURRENT_JOB_SUCCESS = 'SET_CURRENT_JOB_SUCCESS';

// auth actions
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const SET_REFRESH_AND_AUTH_TOKEN = 'SET_REFRESH_AND_AUTH_TOKEN';
